/*  __________           .___      .__  .__                   ___ ________________    ___
 *  \______   \ ____   __| _/____  |  | |__| ____   ____     /  / \__    ___/     \   \  \   
 *   |     ___// __ \ / __ |\__  \ |  | |  |/    \ /  _ \   /  /    |    | /  \ /  \   \  \  
 *   |    |   \  ___// /_/ | / __ \|  |_|  |   |  (  <_> ) (  (     |    |/    Y    \   )  )
 *   |____|    \___  >____ |(____  /____/__|___|  /\____/   \  \    |____|\____|__  /  /  /
 *                 \/     \/     \/             \/           \__\                 \/  /__/
 *                                                                (c) 2018 alf45star
 *                                                        https://github.com/alf45tar/Pedalino
 */


const PROGMEM char listMidiControlChange[] =
    "00 Bank Select|"
    "01 Modulation |"
    "02 Breath Cont|"
    "03 Undefined  |"
    "04 Foot Contro|"
    "05 PortamentoT|"
    "06 DataEntrMSB|"
    "07 Volume     |"
    "08 Balance    |"
    "09 Undefined  |"
    "0A Pan        |"
    "0B Expression |"
    "0C Effect 1   |"
    "0D Effect 2   |"
    "0E Undefined  |"
    "0F Undefined  |"
    "10 GenPurpose1|"
    "11 GenPurpose2|"
    "12 GenPurpose3|"
    "13 GenPurpose4|"
    "14 Undefined  |"
    "15 Undefined  |"
    "16 Undefined  |"
    "17 Undefined  |"
    "18 Undefined  |"
    "19 Undefined  |"
    "1A Undefined  |"
    "1B Undefined  |"
    "1C Undefined  |"
    "1D Undefined  |"
    "1E Undefined  |"
    "1F Undefined  |"
    "20 Bank Select|"
    "21 Modulation |"
    "22 Breath Cont|"
    "23 Undefined  |"
    "24 Foot Contro|"
    "25 Portamento |"
    "26 DataEntrLSB|"
    "27 Volume     |"
    "28 Balance    |"
    "29 Undefined  |"
    "2A Pan        |"
    "2B Expression |"
    "2C Effect 1   |"
    "2D Effect 2   |"
    "2E Undefined  |"
    "2F Undefined  |"
    "30 GenPurpose1|"
    "31 GenPurpose2|"
    "32 GenPurpose3|"
    "33 GenPurpose4|"
    "34 Undefined  |"
    "35 Undefined  |"
    "36 Undefined  |"
    "37 Undefined  |"
    "38 Undefined  |"
    "39 Undefined  |"
    "3A Undefined  |"
    "3B Undefined  |"
    "3C Undefined  |"
    "3D Undefined  |"
    "3E Undefined  |"
    "3F Undefined  |"
    "40 DamperPedal|"
    "41 Portamento |"
    "42 Sostenuto  |"
    "43 Soft Pedal |"
    "44 Legato     |"
    "45 Hold 2     |"
    "46 SoundContr1|"
    "47 SoundContr2|"
    "48 SoundContr3|"
    "49 SoundContr4|"
    "4A SoundContr5|"
    "4B SoundContr6|"
    "4C SoundContr7|"
    "4D SoundContr8|"
    "4E SoundContr9|"
    "4F SoundCont10|"
    "50 GenPurpose5|"
    "51 GenPurpose6|"
    "52 GenPurpose7|"
    "53 GenPurpose8|"
    "54 PortamentoC|"
    "55 Undefined  |"
    "56 Undefined  |"
    "57 Undefined  |"
    "58 HR Velocity|"
    "59 Undefined  |"
    "5A Undefined  |"
    "5B Effects 1  |"
    "5C Effects 2  |"
    "5D Effects 3  |"
    "5E Effects 4  |"
    "5F Effects 5  |"
    "60 Data Inc   |"
    "61 Data Dec   |"
    "62 NRPN LSB   |"
    "63 NRPN MSB   |"
    "64 RPN LSB    |"
    "65 RPN MSB    |"
    "66 Undefined  |"
    "67 Undefined  |"
    "68 Undefined  |"
    "69 Undefined  |"
    "70 Undefined  |"
    "71 Undefined  |"
    "72 Undefined  |"
    "73 Undefined  |"
    "74 Undefined  |"
    "74 Undefined  |"
    "75 Undefined  |"
    "76 Undefined  |"
    "77 Undefined  |"
    "78 AllSoundOff|"
    "79 ResetAllCon|"
    "7A LocalContro|"
    "7B AllNotesOff|"
    "7C OmniModeOff|"
    "7D OmniMode On|"
    "7E MonoMode On|"
    "7F PolyMode On";
